
logLevel = "INFO"

[web]
address = ":8080"

[entryPoints]
  [entryPoints.http]
    address = ":80"

[file]
  [backends]
    [backends.user-service]
      [backends.user-service.servers.server1]
        url = "http://user-service:3000"
    [backend.app-web]
      [backends.app-web.servers.server1]
        url = "http://app-web:3000"

  [frontends]
    [frontends.user-service]
      backend = "user-service"
      entrypoints = ["http"]
    [frontends.user-service.routes.user]
      rule = "Path: /api/users,/api/users/{id},/api/tokens;ReplacePathRegex: ^/api/(.*) /$1"
    [frontends.app-web]
      backend = "app-web"
      entrypoints = ["http"]
    [frontends.app-web.routes.user]
      rule = "HostRegexp:{catchall:.*}"
