---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
      - name: auth-service
        image: badmuts/aula-auth:0.0.1
        ports:
          - containerPort: 3000
        env:
          - name: ACCESS_TOKEN_PUBLIC
            valueFrom:
              secretKeyRef:
                name: jwt-tokens
                key: ACCESS_TOKEN_PUBLIC
          - name: ACCESS_TOKEN_PRIVATE
            valueFrom:
              secretKeyRef:
                name: jwt-tokens
                key: ACCESS_TOKEN_PRIVATE
          - name: REFRESH_TOKEN_PUBLIC
            valueFrom:
              secretKeyRef:
                name: jwt-tokens
                key: REFRESH_TOKEN_PUBLIC
          - name: REFRESH_TOKEN_PRIVATE
            valueFrom:
              secretKeyRef:
                name: jwt-tokens
                key: REFRESH_TOKEN_PRIVATE
          - name: NATS_HOST
            value: nats
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 3
