---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
  labels:
    name: auth-service
spec:
  selector:
    matchLabels:
      app: auth-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: auth-service
        tier: backend
    spec:
      containers:
      - name: auth-service
        image: badmuts/aula-auth:0.0.1
        ports:
          - containerPort: 3000
        env:
          - name: ACCESS_TOKEN_PUBLIC
            valueFrom:
              secretKeyRef:
                name: auth
                key: ACCESS_TOKEN_PUBLIC
          - name: ACCESS_TOKEN_PRIVATE
            valueFrom:
              secretKeyRef:
                name: auth
                key: ACCESS_TOKEN_PRIVATE
          - name: REFRESH_TOKEN_PUBLIC
            valueFrom:
              secretKeyRef:
                name: auth
                key: REFRESH_TOKEN_PUBLIC
          - name: REFRESH_TOKEN_PRIVATE
            valueFrom:
              secretKeyRef:
                name: auth
                key: REFRESH_TOKEN_PRIVATE
          - name: NATS_HOST
            value: nats
