---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  name: course-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: course-service
  template:
    metadata:
      labels:
        app: course-service
    spec:
      containers:
      - name: course-service
        image: badmuts/aula-course:0.0.1
        ports:
          - containerPort: 3000
        env:
          - name: ACCESS_TOKEN_PUBLIC
            valueFrom:
              secretKeyRef:
                name: jwt-tokens
                key: ACCESS_TOKEN_PUBLIC
          - name: DB_HOST
            value: course-db
          - name: DB_DATABASE
            value: course
          - name: DB_USER
            value: course
          # - name: DB_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: course-db
          #       key: password
          - name: NATS_HOST
            value: nats
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 3
