---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nats
  labels:
    name: nats
spec:
  selector:
    matchLabels:
      app: nats
      tier: messaging
  replicas: 1
  template:
    metadata:
      labels:
        app: nats
        tier: messaging
    spec:
      containers:
      - name: nats
        image: nats:1.3.0
        ports:
          - containerPort: 4242
