---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: search-service
  labels:
    name: search-service
spec:
  selector:
    matchLabels:
      app: search-service
      tier: backend
  replicas: 1
  template:
    metadata:
      labels:
        app: search-service
        tier: backend
    spec:
      containers:
      - name: search-service
        image: badmuts/aula-search:0.0.1
        ports:
          - containerPort: 3000
        env:
          - name: ACCESS_TOKEN_PUBLIC
            valueFrom:
              secretKeyRef:
                name: auth
                key: ACCESS_TOKEN_PUBLIC
          - name: NATS_HOST
            value: nats
