---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
      - name: user-service
        image: badmuts/aula-user:0.0.1
        ports:
          - containerPort: 3000
        env:
          - name: ACCESS_TOKEN_PUBLIC
            valueFrom:
              secretKeyRef:
                name: jwt-tokens
                key: ACCESS_TOKEN_PUBLIC
          - name: DB_HOST
            value: user-db
          - name: DB_DATABASE
            value: user
          # - name: DB_USER
          #   value: user
          # - name: DB_PASSWORD
          #   valueFrom:
          #     secretKeyRef:
          #       name: user-db
          #       key: password
          - name: NATS_HOST
            value: nats
        livenessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 300
          periodSeconds: 3
        readinessProbe:
          httpGet:
            path: /healthz
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 3
