version: '3'
services:
  user-service:
    build:
      context: ../../
      dockerfile: packages/user/Dockerfile
    image: badmuts/aula-user:${TAG:-latest}
    ports:
      - "3000:3000"
    volumes:
      - '/usr/src/app/packages/user/node_modules'
      - './:/usr/src/app/packages/user'
    env_file: .env
    command: npx nodemon --exec "npm --prefix packages/user start"
    depends_on:
      - db
      - rabbit

  user-db:
    image: mongo:4.1-xenial

  rabbit:
    image: rabbitmq:management-alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
    ports:
      - "15672:15672"
