#!/usr/bin/env bash
set -e

bold=$(tput bold)
normal=$(tput sgr0)
INFO="${bold}$(tput setaf 2)INFO:   ${normal}"
QUEST="${bold}$(tput setaf 4)QUEST:  ${normal}"

CURRENT=$(git rev-parse --abbrev-ref HEAD | sed 's/\//-/g')-$(git rev-parse HEAD | cut -c1-7)

read -r -p "${QUEST} Version to push?:[${CURRENT}] -> " response
[ -z "${response}" ] && response=${CURRENT}

echo "${INFO} Pushing version ${response}"

TAG=$response docker-compose -f docker-compose.yml push
