name: Build and release
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build and release
      run: |
        docker login -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
        make TAG=$TAG release-ci
      if: github.event.pull_request != ''
      env:
        TAG: ${{github.event.pull_request.head.ref}}-${{github.event.pull_request.head.sha}}
