name: Build and release
on:
  pull_request:
  push:
    branches:
      - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Build and release
      run: |
        docker login -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
        make BRANCH=$BRANCH SHA=$SHA release-ci
      if: github.event_name == 'pull_request'
      env:
        BRANCH: ${{github.event.pull_request.head.ref}}
        SHA: ${{github.event.pull_request.head.sha}}

    - name: Build and release
      run: |
        docker login -u ${{secrets.docker_user}} -p ${{secrets.docker_password}}
        make release-ci
      if: github.event_name == 'push'
      env:
        BRANCH: master
        SHA: ${{github.event.push.head}}
